CREATE TABLE tx_sch.transaction_entries
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transaction_id         UUID           NOT NULL,
    account_id             BIGINT         NOT NULL,
    entry_type             VARCHAR(8)     NOT NULL,
    amount                 NUMERIC(19, 4) NOT NULL,
    currency               VARCHAR(3)     NOT NULL,
    balance_after_amount   NUMERIC(19, 4),
    balance_after_currency VARCHAR(3),
    booked_at              TIMESTAMPTZ    NOT NULL,

    is_deleted             BOOLEAN        NOT NULL DEFAULT FALSE,
    version                BIGINT         NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ,
    created_by             VARCHAR(64),
    updated_at             TIMESTAMPTZ,
    updated_by             VARCHAR(64),

    CONSTRAINT pk_transaction_entries PRIMARY KEY (id),

    -- RESTRICT: moliyaviy yozuv hech qachon kaskad o'chmaydi
    CONSTRAINT fk_entry_transaction_id FOREIGN KEY (transaction_id)
        REFERENCES tx_sch.transactions (id) ON DELETE RESTRICT,

    CONSTRAINT ck_entry_type CHECK (entry_type IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_entry_amount_positive CHECK (amount > 0)
);

CREATE INDEX ix_entry_account_id ON tx_sch.transaction_entries (account_id);
CREATE INDEX ix_entry_transaction_id ON tx_sch.transaction_entries (transaction_id);

COMMENT ON TABLE tx_sch.transaction_entries IS 'Double-entry ledger. Invariant: SUM(DEBIT) = SUM(CREDIT) har bir transaction_id uchun.';
