-- OUTBOX: event DB tranzaksiyasi ICHIDA yoziladi, poller keyin Kafka'ga uzatadi.
CREATE TABLE tx_sch.outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id   VARCHAR(64) NOT NULL,
    event_type     VARCHAR(64) NOT NULL,
    event_id       VARCHAR(64) NOT NULL,
    payload        JSONB       NOT NULL,
    headers        JSONB,
    status         VARCHAR(16) NOT NULL DEFAULT 'NEW',
    attempts       INTEGER     NOT NULL DEFAULT 0,
    last_error     VARCHAR(1024),
    created_at     TIMESTAMPTZ NOT NULL,
    published_at   TIMESTAMPTZ,

    CONSTRAINT pk_outbox_events PRIMARY KEY (id),
    CONSTRAINT uq_outbox_event_id UNIQUE (event_id),
    CONSTRAINT ck_outbox_status CHECK (status IN ('NEW', 'PUBLISHED', 'FAILED'))
);

CREATE INDEX ix_outbox_status_created ON tx_sch.outbox_events (status, created_at);

-- INBOX: Kafka at-least-once beradi. Bir event ikki marta kelsa,
-- UNIQUE(event_id) ikkinchi urinishni DB darajasida to'xtatadi.
CREATE TABLE tx_sch.processed_events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id     VARCHAR(64) NOT NULL,
    event_type   VARCHAR(64) NOT NULL,
    source       VARCHAR(64) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_processed_events PRIMARY KEY (id),
    CONSTRAINT uq_processed_event_id UNIQUE (event_id)
);
