CREATE TABLE tx_sch.saga_states
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transaction_id UUID        NOT NULL,
    status         VARCHAR(24) NOT NULL,
    current_step   VARCHAR(24) NOT NULL,
    payload        JSONB,
    retry_count    INTEGER     NOT NULL DEFAULT 0,
    last_error     VARCHAR(1024),
    version        BIGINT      NOT NULL DEFAULT 0,
    started_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ,

    CONSTRAINT pk_saga_states PRIMARY KEY (id),
    CONSTRAINT uq_saga_transaction_id UNIQUE (transaction_id),
    CONSTRAINT fk_saga_transaction_id FOREIGN KEY (transaction_id)
        REFERENCES tx_sch.transactions (id) ON DELETE RESTRICT,
    CONSTRAINT ck_saga_status CHECK (status IN
        ('STARTED', 'DEBITED', 'CREDITED', 'COMPLETED', 'COMPENSATING', 'COMPENSATED', 'FAILED'))
);

COMMENT ON TABLE tx_sch.saga_states IS 'Choreography saga persistent holati. Service restart bo''lsa, yarim qolgan saga shu yerdan topiladi.';
