CREATE TABLE tx_sch.scheduled_payments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT         NOT NULL,
    source_account_id BIGINT         NOT NULL,
    target_account_id BIGINT         NOT NULL,
    amount            NUMERIC(19, 4) NOT NULL,
    currency          VARCHAR(3)     NOT NULL,
    frequency         VARCHAR(16)    NOT NULL,
    next_execution_at TIMESTAMPTZ    NOT NULL,
    last_execution_at TIMESTAMPTZ,
    end_at            TIMESTAMPTZ,
    execution_count   INTEGER        NOT NULL DEFAULT 0,
    is_active         BOOLEAN        NOT NULL DEFAULT TRUE,
    quartz_job_key    VARCHAR(128),
    description       VARCHAR(255),

    is_deleted        BOOLEAN        NOT NULL DEFAULT FALSE,
    version           BIGINT         NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ,
    created_by        VARCHAR(64),
    updated_at        TIMESTAMPTZ,
    updated_by        VARCHAR(64),

    CONSTRAINT pk_scheduled_payments PRIMARY KEY (id),
    CONSTRAINT ck_sched_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_sched_frequency CHECK (frequency IN ('ONCE', 'DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT ck_sched_different_accounts CHECK (source_account_id <> target_account_id)
);

CREATE INDEX ix_sched_next_execution ON tx_sch.scheduled_payments (is_active, next_execution_at);
