-- Idempotency'ning IKKINCHI qatlami. Redis o'chsa ham pul ikki marta ketmaydi.
CREATE TABLE tx_sch.idempotency_records
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT      NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    request_hash    VARCHAR(64) NOT NULL,
    response_body   TEXT,
    http_status     INTEGER,
    created_at      TIMESTAMPTZ NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_idempotency_records PRIMARY KEY (id),
    CONSTRAINT uq_idem_user_key UNIQUE (user_id, idempotency_key)
);

CREATE INDEX ix_idem_expires_at ON tx_sch.idempotency_records (expires_at);
