CREATE TABLE tx_sch.fraud_checks
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transaction_id UUID          NOT NULL,
    rule_code      VARCHAR(32)   NOT NULL,
    decision       VARCHAR(16)   NOT NULL,
    score          NUMERIC(5, 4),
    reason         VARCHAR(512),
    checked_at     TIMESTAMPTZ   NOT NULL,

    CONSTRAINT pk_fraud_checks PRIMARY KEY (id),
    CONSTRAINT ck_fraud_decision CHECK (decision IN ('ALLOW', 'REVIEW', 'BLOCK'))
);

CREATE INDEX ix_fraud_transaction_id ON tx_sch.fraud_checks (transaction_id);

COMMENT ON TABLE tx_sch.fraud_checks IS 'Har bir rule alohida satr: regulyator "nega bloklandi?" deb so''raganda javob bor.';
